import Config

# Configure your database
config :ieee_tamu_portal, IeeeTamuPortal.Repo,
  username: "portal",
  password: "portal",
  hostname: "localhost",
  database: "portal_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to loopback ipv4 address prevents access from other machines.
config :ieee_tamu_portal, IeeeTamuPortalWeb.Endpoint,
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "J7pk/dbOQk2yphdnZ4RZRuC8Do2yoWoq4NEPHaoSB7eLMNFZtHg4gCUn50sLyqcO",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:ieee_tamu_portal, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:ieee_tamu_portal, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :ieee_tamu_portal, IeeeTamuPortalWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ieee_tamu_portal_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :ieee_tamu_portal, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# ## Cloudflare R2

bucket =
  System.get_env("R2_BUCKET")

account_id =
  System.get_env("CF_ACCOUNT_ID")

access_key_id =
  System.get_env("R2_BUCKET_KEY_ID")

secret_access_key =
  System.get_env("R2_BUCKET_ACCESS_KEY")

config :ieee_tamu_portal, IeeeTamuPortalWeb.Upload.SimpleS3Upload,
  region: "auto",
  access_key_id: access_key_id,
  secret_access_key: secret_access_key,
  url: "https://#{bucket}.#{account_id}.r2.cloudflarestorage.com"

config :ieee_tamu_portal, IeeeTamuPortalWeb.Auth.AdminAuth,
  username: "admin",
  password: "password"

config :open_api_spex, :cache_adapter, OpenApiSpex.Plug.NoneCache

# Discord OAuth configuration for development
config :ieee_tamu_portal, :discord_oauth,
  client_id: System.get_env("DISCORD_CLIENT_ID", "your_discord_client_id"),
  client_secret: System.get_env("DISCORD_CLIENT_SECRET", "your_discord_client_secret"),
  redirect_uri: "http://localhost:4000/auth/discord/callback"

# Discord Bot API configuration for development
config :ieee_tamu_portal,
       :discord_bot_url,
       System.get_env("DISCORD_BOT_URL", "http://localhost:3000")
